const UserActionTypes = {
  LOG_IN_START: "LOG_IN_START",
  LOG_IN_SUCCESS: "LOG_IN_SUCCESS",
  LOG_IN_FAILURE: "LOG_IN_FAILURE",
  AUTHENTICATION_SUCCESS: "AUTHENTICATION_SUCCESS",
};

export default UserActionTypes;