const TasksActionTypes = {
  LOADING_TASKS: 'LOADING_TASKS',
  TASKS_LOADED: 'TASKS_LOADED',
  ADD_TASK: 'ADD_TASK',
  NEW_TASK_PROCESS: 'NEW_TASK_PROCESS',
  TASK_FAILURE: 'TASK_FAILURE',
  DELETE_TASK: 'DELETE_TASK',
  EDIT_TASK: 'EDIT_TASK',
  GET_SPECIFIC_TASK: 'GET_SPECIFIC_TASK',
  REMOVE_CURRENT_TASK: 'REMOVE_CURRENT_TASK',
  GET_USER_TASKS: 'GET_USER_TASKS',
  GET_ASSIGNED_TASKS: 'GET_ASSIGNED_TASKS',
};

export default TasksActionTypes;