const TasksActionTypes = {
  LOADING_TASKS: 'LOADING_TASKS',
  TASKS_LOADED: 'TASKS_LOADED',
  ADD_TASK: 'ADD_TASK',
  DELETE_TASK: 'DELETE_TASK',
  EDIT_TASK: 'EDIT_TASK',
  SET_CURRENT_TASK: 'SET_CURRENT_TASK',
  REMOVE_CURRENT_TASK: 'REMOVE_CURRENT_TASK',
  GET_USER_TASKS: 'GET_USER_TASKS',
  GET_TASKS_ASSIGNED: 'GET_TASKS_ASSIGNED',
};

export default TasksActionTypes;